### PR TITLE
Fix mpiio with stdlibc++ range checking

### LINKED ISSUE #3230: mpiio tests fails on i686 with espresso-4.1.0
```
130/135 Test #127: mpiio .........................................***Failed    1.83 sec
/usr/include/c++/9/bits/stl_vector.h:1042: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = int; _Alloc = std::allocator<int>; std::vector<_Tp, _Alloc>::reference = int&; std::vector<_Tp, _Alloc>::size_type = unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 22870 RUNNING AT buildvm-12.phx2.fedoraproject.org
=   EXIT CODE: 134
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```

Details [here](https://github.com/espressomd/espresso/files/3683130/build_i686.log.txt)

### PR DESCRIPTION
**Pull request by mkuron**
Fixes #3230. Reported by @junghans.

When mpiio was used but no bonds were present, we would still try to copy zero bonds from a zero-length vector. This triggered an assertion when stdlibc++ range checking was enabled.

Please tag for cherry-picking into 4.1.1.

### CODE REVIEW

**Review by jngrad — APPROVED** [review]

File: src/core/io/mpiio/mpiio.cpp [hunk 1]
```diff
@@ -446,9 +446,11 @@ void mpi_mpiio_common_read(const char *filename, unsigned fields) {
 
     for (int i = 0; i < nlocalpart; ++i) {
       int blen = boff[i + 1] - boff[i];
-      auto &bl = local_particles[id[i]]->bl;
-      bl.resize(blen);
-      std::copy_n(&bond[boff[i]], blen, bl.begin());
+      if (blen) {
+        auto &bl = local_particles[id[i]]->bl;
+        bl.resize(blen);
+        std::copy_n(&bond[boff[i]], blen, bl.begin());
```
Comment (fweik) [inline src/core/io/mpiio/mpiio.cpp]: I think it  would be better to use `std::vector::data` instead of taking the address of the first element. That makes the intent clearer, and works also with an empty vector, and hence also does not need the check.

**Review by fweik — CHANGES_REQUESTED** [review]

File: src/core/io/mpiio/mpiio.cpp (hunk 1 above)
Comment (mkuron) [reply src/core/io/mpiio/mpiio.cpp]: I don‘t think `bond.data() + boff[i]` is that much clearer than `&bond[boff[i]].` Most people reading code tend to be confused by pointer arithmetic like this.

Comment (fweik) [reply src/core/io/mpiio/mpiio.cpp]: I don't agree, this is not incidental, but the offset calculation is the actual logic here. Also getting rid of the control structure is worth it. We can also do iterator arithmetic instead if you think that is less scary.

**Comment by hirschsn** [comment]
I tend to think that the C++ implementation used in #3230 is broken in this case. The standard states for copy_n:
"Effects: For each non-negative integer i < n, performs *(result + i) = *(first + i)."

If an implementation for copy_n asserts: `__n < this->size()`, the implementation forgot the corner case: `__n == 0`. Or am I missing something here?

Nonetheless, this PR looks good because it is an easy workaround for the problem.

File: src/core/io/mpiio/mpiio.cpp [hunk 2]
```diff
@@ -446,9 +446,11 @@ void mpi_mpiio_common_read(const char *filename, unsigned fields) {
 
     for (int i = 0; i < nlocalpart; ++i) {
       int blen = boff[i + 1] - boff[i];
-      auto &bl = local_particles[id[i]]->bl;
-      bl.resize(blen);
-      std::copy_n(&bond[boff[i]], blen, bl.begin());
+      if (blen) {
```
Comment (hirschsn) [inline src/core/io/mpiio/mpiio.cpp]: I'd actually suggest a `if (blen > 0)` here, because `blen` is not a bool and not an int pretending to be.

**Comment by mkuron** [comment]
@hirschsn, the assertion is not inside `std::copy_n`, but in `std::vector::operator[]`. And that's standard-compliant because subscripting beyond bounds is undefined.

File: src/core/io/mpiio/mpiio.cpp (hunk 1 above)
Comment (mkuron) [reply src/core/io/mpiio/mpiio.cpp]: using iterator arithmetic now

**Review by fweik — APPROVED** [review]

**Comment by hirschsn** [comment]
@mkuron I see. That makes sense. :)

Wouldn't `bond.begin() + off` where `off == 0` in this case fix the problem already?

NVM, I see that's what you've done.

**Comment by mkuron** [comment]
Build is failing because of https://github.com/espressomd/espresso/issues/3235, which is fixed by https://github.com/espressomd/docker/pull/139.

**Comment by jngrad** [comment]
bors r=fweik

**Comment by jngrad** [comment]
bors r-
(failed CI)

**Comment by jngrad** [comment]
bors r=fweik
