### PR TITLE
Always define q

### LINKED ISSUE #2248: MDA_ESP does not work without ELECTROSTATICS
Also I think there is no test.

### PR DESCRIPTION
**Pull request by pdebuyl**
Fixes #2248 (tentative)

Description of changes:
 - remove preprocessor barriers to the definition of `q` as a particle propertpy
 - goal: avoid failure when a feature "blindly" accesses q (here, for the MDA sample)

I file the PR now to get an idea of the CI result, as I could only test a limited number of configurations.

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

### CODE REVIEW

**Comment by fweik** [comment]
This probably means that a lot of `ifdef`'s can be removed.

File: src/core/particle_data.cpp [hunk 1]
```diff
@@ -598,6 +598,10 @@ int set_particle_q(int part, double q) {
   mpi_send_q(pnode, part, q);
   return ES_OK;
 }
+#ifndef ELECTROSTATICS
+const constexpr double ParticleProperties::q;
```
Comment (KaiSzuttor) [inline src/core/particle_data.cpp]: you can drop the const here

**Comment by pdebuyl** [comment]
Should I hunt down the `#ifdef ELECTROSTATICS` that protect access to q?

File: src/core/particle_data.cpp (hunk 1 above)
Comment (fweik) [reply src/core/particle_data.cpp]: No, `const` is needed in C++11, `constexpr` only implies `const` in C++14 an newer.

Comment (KaiSzuttor) [reply src/core/particle_data.cpp]: are you sure?
https://stackoverflow.com/questions/28845058/constexpr-const-vs-constexpr-variables
https://stackoverflow.com/questions/14116003/difference-between-constexpr-and-const

**Comment by fweik** [comment]
@pdebuyl that would be helpful. There is at least one for which the performance impact needs to be checked (the one in the pair force calculation).

**Comment by pdebuyl** [comment]
next week :-)

**Review by fweik — APPROVED** [review]
