### PR TITLE
CUDA exception handling

### LINKED ISSUE #4085: -lcuda needs to be removed for cuda-11.2
At least in the installation done by spack, libcuda is not present, there is just libcudart.
This needs to be changed in cmake/FindCUDACompilerNVCC.cmake.
Don't know if -lcuda is needed for older cuda versions.

### PR DESCRIPTION
**Pull request by jngrad**
Description of changes:
- convert CUDA error codes into runtime errors using the message associated to the error code
- properly handle CUDA errors by halting the flow of the program instead of ignoring them (Barnes-Hut, LB GPU)
- remove superfluous CUDA global variables (partial fix for #2628)
- restore `cuda_gather_gpus()` functionality and convert the `device_list()` getter to a regular function (API change)
- remove unused `libcuda` dependency (fixes #4085)

### CODE REVIEW

File: src/core/cuda_init.cpp [hunk 1]
```diff
@@ -49,49 +51,50 @@ struct CompareDevices {
...
- *  be more than one on one node.
+ *  It relies on <tt>MPI_Get_processor_name()</tt> to get a unique identifier
+ *  of the physical node, as opposed to the logical rank of which there can
+ *  be more than one per node.
  */
-std::vector<EspressoGpuDevice> cuda_gather_gpus() {
-  int n_gpus = cuda_get_n_gpus();
-  char proc_name[MPI_MAX_PROCESSOR_NAME];
-  int proc_name_len;
+static std::vector<EspressoGpuDevice> mpi_cuda_gather_gpus_local() {
```
Comment (KaiSzuttor) [inline src/core/cuda_init.cpp:58]: why do we collect cuda devices if we only support devices on the head node?

File: src/core/cuda_utils.cuh [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+#error Do not include CUDA headers in normal C++-code!!!
+#endif
+
+#include "cuda_utils.hpp"
+
+#include <cuda.h>
+
+#include <string>
+
+class cuda_runtime_error_impl : public cuda_runtime_error {
```
Comment (KaiSzuttor) [inline src/core/cuda_utils.cuh]: not sure if the suffix is appropriate here

File: src/core/cuda_utils.cuh [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+
+/** CUDA streams for parallel computing on CPU and GPU */
+extern cudaStream_t stream[1];
+
+/** Error output for memory allocation and memory copy
+ *  @param err   cuda error code
+ *  @param file  .cu file were the error took place
+ *  @param line  line of the file were the error took place
+ */
+void _cuda_safe_mem(cudaError_t err, const char *file, unsigned int line);
```
Comment (KaiSzuttor) [inline src/core/cuda_utils.cuh]: we should not use underscores at the beginning of identifiers, IMHO

File: src/python/espressomd/cuda_init.pyx [hunk 4]
```diff
@@ -52,35 +51,72 @@ cdef class CudaInitHandle:
...
+                devices = cuda_gather_gpus()
+            except RuntimeError:
+                pass
+            resources = dict()
+            for i in range(devices.size()):
+                dev = devices[i]
+                hostname = utils.to_str(dev.proc_name)
+                if hostname not in resources:
+                    resources[hostname] = {}
+                resources[hostname][dev.id] = {
```
Comment (KaiSzuttor) [inline src/python/espressomd/cuda_init.pyx:103]: can't we get the device as a string directly?

File: testsuite/python/gpu_availability.py [hunk 5]
```diff
@@ -17,21 +17,61 @@
...
+            with self.assertRaisesRegex(RuntimeError, error_msg):
+                self.system.cuda_init_handle.device = n_gpus + 1
+        else:
+            with self.assertRaisesRegex(RuntimeError, error_msg):
+                self.system.cuda_init_handle.device
+            with self.assertRaisesRegex(RuntimeError, error_msg):
+                self.system.cuda_init_handle.device = 0
+
+    @utx.skipIfMissingGPU()
+    def test_devices(self):
```
Comment (KaiSzuttor) [inline testsuite/python/gpu_availability.py]: what's the purpose of this test?

File: src/core/cuda_init.cpp (hunk 1 above)
Comment (jngrad) [reply src/core/cuda_init.cpp:58]: That's how it was originally written. Should I remove the MPI functionality?

File: src/python/espressomd/cuda_init.pyx (hunk 4 above)
Comment (jngrad) [reply src/python/espressomd/cuda_init.pyx:103]: The string returned by `cudaGetDeviceProperties()` cannot be used as a key: we only collect the first 64 characters of the string returned by the CUDA function. I'm not sure why we truncate it, it was written like this 6 years ago and the commit message doesn't say anything, and there is not comment to explain it. Maybe back different CUDA versions had different char array lengths?

File: src/core/cuda_init.cpp (hunk 1 above)
Comment (KaiSzuttor) [reply src/core/cuda_init.cpp:58]: no, i was just wondering, why we have the functionality...

File: testsuite/python/gpu_availability.py (hunk 5 above)
Comment (jngrad) [reply testsuite/python/gpu_availability.py]: Not a good test name. It tests the `list_devices*()` methods.

File: src/core/cuda_init.cpp (hunk 1 above)
Comment (jngrad) [reply src/core/cuda_init.cpp:58]: This functionality was introduced in the Tcl days and wasn't ported to the python interface until now. I wouldn't mind removing the MPI functionality, since we only support devices on the head nodes. It's also cumbersome to find the local MPI rank name in python to get the correct dict key...

File: src/python/espressomd/cuda_init.pyx (hunk 4 above)
Comment (KaiSzuttor) [reply src/python/espressomd/cuda_init.pyx:103]: i meant to get a string representation of ```cudaDeviceProp``` right in the core instead of building it on the python level

Comment (jngrad) [reply src/python/espressomd/cuda_init.pyx:103]: Sorry, I don't get what you mean. On this line we're building a dict. Most of the device properties the user is interested in are integers.

Comment (KaiSzuttor) [reply src/python/espressomd/cuda_init.pyx:103]: oh, I was missing the dict, thought we only want to print the information, sorry

**Review by KaiSzuttor — APPROVED** [review]
