### PR TITLE
Disable box length reset when particles are present

### LINKED ISSUE #4834: Box length change invalidates particle positions
When manually modifying the box length, the new particle positions are recalculated with the wrong box size.

MWE:
```python
import espressomd
import numpy as np
np.set_printoptions(precision=2)
system = espressomd.System(box_l=[15., 15., 15.])
system.time_step = 0.01
system.cell_system.skin = 0.4
p = system.part.add(pos=[-0.1, 15.1, 30.])
expected = p.pos_folded * 10./15.
print(f"before:   {p.pos_folded}")
system.box_l = [10., 10., 10.]
print(f"after:    {p.pos_folded}")
print(f"expected: {expected}")
```
Output:
```
before:   [14.90 0.10 0. ]
after:    [ 4.90 0.10 0. ]
expected: [ 9.93 0.07 0. ]
```

This bug is reproducible on the python branch and with ESPResSo releases 4.2.1 and 4.1.4.

It is unclear to me, how to gracefully handle a box resize. One could fold the particle position onto the unit cell, apply the box resize via rescaling, and re-use the older image box counter. But then, a jump may become visible in trajectories in unfolded coordinates. One would also need to maintain the old and new value in the `BoxGeometry` object to apply the folding and then unfolding with the two box sizes. It is also unclear what should happen with Lees-Edwards boundary conditions, where particle positions gain an offset when going through one of the three periodic boundaries.

The easiest course of action is to prevent manually changing the box length if the box contains particles, and rely instead on the `system.change_volume_and_rescale_particles()`, which implements the correct behavior. Alternatively, one could make the box length setter call the rescale method under-the-hood, but this introduces a new problem: the `on_boxl_change` event would be called three times, causing long-range solvers to re-tune all solver parameters three times with a different box size. Since  the box might no longer be cubic for the first two re-tunes, the tuning code may become extremely slow, have to sample more mesh sizes, and throw an exception if the accuracy cannot be reached.

Note: this bug doesn't affect the NpT integrator, which uses the rescale algorithm.

### PR DESCRIPTION
**Pull request by jngrad**
Fixes #4834

Description of changes:
- Resizing the box via `system.box_l = new_box_l` now throws a runtime error if there are particles present, because particle position folding cannot be guaranteed to be correct; use `system.change_volume_and_rescale_particles()` instead, which properly rescales particle positions.

### CODE REVIEW

File: src/script_interface/system/System.cpp [hunk 1]
```diff
@@ -111,6 +111,7 @@ System::System() : m_instance{}, m_leaves{std::make_shared<Leaves>()} {
            if (not(new_value > Utils::Vector3d::broadcast(0.))) {
              throw std::domain_error("Attribute 'box_l' must be > 0");
            }
+           m_instance->veto_boxl_change();
            m_instance->box_geo->set_length(new_value);
            m_instance->on_boxl_change();
```
Comment (jngrad) [inline src/script_interface/system/System.cpp:116]: Note to reviewers: there are long-term plans to replace this clumsy `veto/on_change` mechanism by a proper message-passing interface (#4762).

**Review by reinaual — APPROVED** [review]
I think we should add this change as a major one in the release-notes, to make sure it is as visible as possible to the users. This has a lot of potential to break old scripts, especially custom checkpointing solutions
