### PR TITLE
Lb test merge and fixes

### LINKED ISSUE #2019: GPU LB: external force gives wrong velocity
M(not)WE:
``` python
import numpy as np

import espressomd
import espressomd.lb

system = espressomd.System(box_l = [10] * 3)
system.cell_system.skin = 0.1
system.time_step = 0.01
ext_force = [3.5, 0.0, 0.0]
tau = system.time_step
dens = 3.0
lbf = espressomd.lb.LBFluidGPU(tau=tau, agrid=.5, visc=1.0, dens=dens, fric=2.0, ext_force=ext_force) 
system.actors.add(lbf)

system.integrator.run(10)
print("Expexted: {}, got: {}".format(np.array(ext_force) * 9.5 *tau / dens, lbf[0, 0, 0].velocity))
```

### PR DESCRIPTION
**Pull request by RudolfWeeber**
Fixes #2019.

This merges the lb.py and lb_gpu.py test cases into lb_comon.py.
lb_cpu and lb_gpu tests only specify the lb class to use and the precision.

core fixes:
* cuda_common: Prevent double frees
* lb fields resetting: Changing lb parameters or initializing now results in a reset lb fluid. Before that, something halfway happened.

* Fix double ext_force_density application in 1st time step

@KaiSzuttor, could you take a look at this?

### CODE REVIEW

File: src/core/lb.cpp [hunk 1]
```diff
@@ -499,8 +499,14 @@ int lb_lbfluid_set_ext_force_density(int component, double p_fx, double p_fy,
     lbpar_gpu.ext_force_density[3 * component + 0] = (float)p_fx;
     lbpar_gpu.ext_force_density[3 * component + 1] = (float)p_fy;
     lbpar_gpu.ext_force_density[3 * component + 2] = (float)p_fz;
-    lbpar_gpu.external_force_density = 1;
+    if (p_fx != 0 || p_fy !=0 || p_fz != 0) {
```
Comment (KaiSzuttor) [inline src/core/lb.cpp:502]: this check can happen before setting the ext_force_density for ```lbpar_gpu```

File: src/core/lb.cpp [hunk 2]
```diff
@@ -2089,6 +2095,16 @@ void lb_reinit_force_densities() {
 
 /** (Re-)initializes the fluid according to the given value of rho. */
 void lb_reinit_fluid() {
+  if (lattice_switch == LATTICE_LB_GPU){
+
```
Comment (KaiSzuttor) [inline src/core/lb.cpp]: pls remove empty line

File: src/core/lb.cpp [hunk 3]
```diff
@@ -2089,6 +2095,16 @@ void lb_reinit_force_densities() {
...
+  if (lattice_switch == LATTICE_LB_GPU){
+    
+    #ifdef LB_GPU
+      lb_reinit_fluid_gpu();
+    #endif
+  }
+  else if (lattice_switch == LATTICE_LB) {
+  auto old_size=lbfields.size();
+  lbfields.resize(0);
+  lbfields.resize(old_size);
```
Comment (KaiSzuttor) [inline src/core/lb.cpp]: ```std::fill(lbfields.begin(), lbfields.end(), LB_FluidNode());``` instead of the three lines.

File: src/core/lb.cpp [hunk 4]
```diff
@@ -2115,7 +2131,14 @@ void lb_reinit_fluid() {
   LBBoundaries::lb_init_boundaries();
 #endif // LB_BOUNDARIES
 }
+else
+  throw std::runtime_error("lb_reinit_fluid called without an lb being active");
```
Comment (KaiSzuttor) [inline src/core/lb.cpp]: lb -> LB fluid

File: src/python/espressomd/lb.pyx [hunk 5]
```diff
@@ -120,25 +120,23 @@ IF LB_GPU or LB:
...
+            if python_lbfluid_set_ext_force_density(self._params["ext_force_density"]):
+                raise Exception("lb_lbfluid_set_ext_force_density error")
 
-            if not self._params["couple"] == default_params["couple"]:
-                if python_lbfluid_set_couple_flag(self._params["couple"]):
-                    raise Exception("lb_lbfluid_set_couple_flag error")
-            utils.handle_errors("LB activation")
+            if python_lbfluid_set_couple_flag(self._params["couple"]):
+                raise Exception("lb_lbfluid_set_couple_flag error")
+            utils.handle_errors("lb activation")
```
Comment (KaiSzuttor) [inline src/python/espressomd/lb.pyx]: LBFluid activation

File: src/python/espressomd/lb.pyx [hunk 6]
```diff
@@ -226,8 +224,10 @@ IF LB_GPU or LB:
         ####################################################
         def _activate_method(self):
             self.validate_params()
-            self._set_params_in_es_core()
             self._set_lattice_switch()
+            self._set_params_in_es_core()
+            mpi_lb_init()
+            utils.handle_errors("lb activation")
```
Comment (KaiSzuttor) [inline src/python/espressomd/lb.pyx]: LBFluid activation

File: src/python/espressomd/lb.pyx [hunk 7]
```diff
@@ -244,12 +244,12 @@ IF LB_GPU:
 
         """
 
+        def remove_total_momentum(self):
+            lb_lbfluid_remove_total_momentum()
```
Comment (KaiSzuttor) [inline src/python/espressomd/lb.pyx:250]: please insert a blank line here

File: testsuite/lb_common.py [hunk 8]
```diff
@@ -78,13 +76,15 @@ def test_mass_momentum_thermostat(self):
...
         self.system.thermostat.turn_off()
 
-        self.lbf = lb.LBFluid(
+        self.lbf = self.lb_class(
             visc=self.params['viscosity'],
             dens=self.params['dens'],
             agrid=self.params['agrid'],
             tau=self.system.time_step,
             fric=self.params['friction'], ext_force_density=[0, 0, 0])
+        print("0",self.system.analysis.analyze_linear_momentum())
```
Comment (KaiSzuttor) [inline testsuite/lb_common.py]: please remove print statements

File: testsuite/lb_cpu.py [hunk 9]
```diff
@@ -0,0 +1,24 @@
+
+# Basic tests of the Lattice Boltzmann implementation
```
Comment (KaiSzuttor) [inline testsuite/lb_cpu.py]: Please remove the documentation here since this information is already given in the common file and we don't want to maintain two places for the test documentation.

File: testsuite/lb_cpu.py [hunk 10]
```diff
@@ -0,0 +1,24 @@
...
+
+from __future__ import print_function
+import unittest as ut
+import lb_common
+import espressomd
+import espressomd.lb as lb
+
+
+
+if espressomd.has_features("LB_GPU"):
```
Comment (KaiSzuttor) [inline testsuite/lb_cpu.py]: you can omit this check here

File: testsuite/lb_gpu.py [hunk 11]
```diff
@@ -1,161 +1,24 @@
-# Basic tests of the Lattice Boltzmann implementation       
-#                                                           
-# 1) check conservation of fluid mass                       
-# 2) check conservation of total momentum                   
-# 3) measure temperature of colloid and fluid  
+
+# Basic tests of the Lattice Boltzmann implementation
```
Comment (KaiSzuttor) [inline testsuite/lb_gpu.py]: Please also remote the test documentation here

**Review by KaiSzuttor — CHANGES_REQUESTED** [review]

**Comment by RudolfWeeber** [comment]
On Tue, Jul 24, 2018 at 01:45:38PM -0700, Kai Szuttor wrote:
> > @@ -499,8 +499,14 @@ int lb_lbfluid_set_ext_force_density(int component, double p_fx, double p_fy,
>      lbpar_gpu.ext_force_density[3 * component + 0] = (float)p_fx;
>      lbpar_gpu.ext_force_density[3 * component + 1] = (float)p_fy;
>      lbpar_gpu.ext_force_density[3 * component + 2] = (float)p_fz;
> -    lbpar_gpu.external_force_density = 1;
> +    if (p_fx != 0 || p_fy !=0 || p_fz != 0) {
> 
> this check can happen before setting the ext_force_density for ```lbpar_gpu```
I'd prefer to set both, the correct value and the correct flag, just
to be sure. So I left this.


 
> +if espressomd.has_features("LB_GPU"): 
> 
> you can omit this check here
The feature guards in lb_cpu and lb_gpu.py need to be there, becuase
the LBFluid classes don't exist otherwise.
I corrected the one in lb_cpu.py, though.

Rest is done, I think

**Review by KaiSzuttor — APPROVED** [review]

File: src/python/espressomd/lb.pyx [hunk 12]
```diff
@@ -226,8 +224,10 @@ IF LB_GPU or LB:
         ####################################################
         def _activate_method(self):
             self.validate_params()
-            self._set_params_in_es_core()
             self._set_lattice_switch()
+            self._set_params_in_es_core()
+            mpi_lb_init()
```
Comment (KaiSzuttor) [inline src/python/espressomd/lb.pyx]: this call has to be guarded for shanchen?

**Comment by RudolfWeeber** [comment]
I (hopefully) fixed builds without LB(cpu) which includes the ShanChen myconfig.
I also disabled the lb_gpu test when ShanChen is present (as was the case previously).
We decided to defer Shanchen to 4.1, anyway.
