### PR TITLE
WIP: Re-introducing three point coupling

### LINKED ISSUE #2517: LB: three point coupling gives wrong results

### PR DESCRIPTION
**Pull request by KaiSzuttor**
Fixes #2517

Description of changes:
 - reimplementation of three-point interpolation
 - added tests

### CODE REVIEW

File: src/core/grid_based_algorithms/lb_interpolation.cpp [hunk 1]
```diff
@@ -8,10 +9,37 @@
...
 #include "lbgpu.hpp"
 
+namespace {
+
+InterpolationOrder interpolation_order = InterpolationOrder::linear;
+}
+
+void mpi_set_interpolation_order_slave(int order, int) {
+  if (order == 0) {
+    interpolation_order = InterpolationOrder::linear;
```
Comment (fweik) [inline src/core/grid_based_algorithms/lb_interpolation.cpp]: You can do `interpolation_order = InterpolationOrder{order}` without the switch, then you don't have to hard-code the values.

File: src/core/grid_based_algorithms/lb_interpolation.cpp [hunk 2]
```diff
@@ -8,10 +9,37 @@
...
+    interpolation_order = InterpolationOrder::quadratic;
+  }
+}
+
 #if defined(LB) || defined(LB_GPU)
 
-namespace {
+void lb_lbinterpolation_set_interpolation_order(
+    InterpolationOrder const &interpolation_order) {
+  if (interpolation_order == InterpolationOrder::linear) {
```
Comment (fweik) [inline src/core/grid_based_algorithms/lb_interpolation.cpp]: I think it is cleaner to just do
```c++
switch(interpolation_order) {
  case InterpolationOrder::linear:
  case InterpolationOrder::quadratic:
    mpi_call(interpolation_order_slave, static_cast<int>(interpolation_order));
    mpi_set_interpolation_order_slave(static_cast<int>(interpolation_order), 0);
}
```
or skip the switch if the value checking is not needed. This way you can avoid hard-coding the values, and a compiler warning is emitted if one of the cases is not handled.

File: src/core/grid_based_algorithms/lb_interpolation.cpp [hunk 3]
```diff
@@ -72,12 +100,21 @@ lb_lbinterpolation_get_interpolated_velocity_global(const Vector3d &pos) {
   if (lattice_switch & LATTICE_LB_GPU) {
 #ifdef LB_GPU
     Vector3d interpolated_u{};
-    lb_get_interpolated_velocity_gpu(folded_pos.data(), interpolated_u.data(),
-                                     1);
+    if (interpolation_order == InterpolationOrder::linear) {
```
Comment (fweik) [inline src/core/grid_based_algorithms/lb_interpolation.cpp]: `switch(interpolation_order)`

File: src/core/grid_based_algorithms/lb_interpolation.cpp [hunk 4]
```diff
@@ -72,12 +100,21 @@ lb_lbinterpolation_get_interpolated_velocity_global(const Vector3d &pos) {
...
+                                       1, false);
+    } else if (interpolation_order == InterpolationOrder::quadratic) {
+      lb_get_interpolated_velocity_gpu(folded_pos.data(), interpolated_u.data(),
+                                       1, true);
+    }
     return interpolated_u;
 #endif
   } else if (lattice_switch & LATTICE_LB) {
 #ifdef LB
+    if (interpolation_order == InterpolationOrder::quadratic) {
```
Comment (fweik) [inline src/core/grid_based_algorithms/lb_interpolation.cpp]: `switch(interpolation_order)`

File: src/core/grid_based_algorithms/lb_interpolation.cpp [hunk 5]
```diff
@@ -92,6 +129,10 @@ lb_lbinterpolation_get_interpolated_velocity_global(const Vector3d &pos) {
 #ifdef LB
 void lb_lbinterpolation_add_force_density(const Vector3d &pos,
                                           const Vector3d &force_density) {
+  if (interpolation_order == InterpolationOrder::quadratic) {
```
Comment (fweik) [inline src/core/grid_based_algorithms/lb_interpolation.cpp]: `switch(interpolation_order)`

File: src/core/grid_based_algorithms/lb_particle_coupling.cpp [hunk 6]
```diff
@@ -168,13 +168,26 @@ void lb_lbcoupling_calc_particle_lattice_ia(bool couple_virtual) {
   ESPRESSO_PROFILER_CXX_MARK_FUNCTION;
   if (lattice_switch & LATTICE_LB_GPU) {
 #ifdef LB_GPU
-    if (lb_particle_coupling.couple_to_md && this_node == 0)
-      lb_calc_particle_lattice_ia_gpu(couple_virtual,
-                                      lb_lbcoupling_get_gamma());
+    if (lb_particle_coupling.couple_to_md && this_node == 0) {
+      if (lb_lbinterpolation_get_interpolation_order() ==
```
Comment (fweik) [inline src/core/grid_based_algorithms/lb_particle_coupling.cpp]: `switch(interpolation_order)`

File: src/python/espressomd/lb.pyx [hunk 7]
```diff
@@ -174,6 +174,20 @@ cdef class HydrodynamicInteraction(Actor):
 
             return self._params
 
+        def set_interpolation_order(self, interpolation_order):
+            """ Set the order for the fluid interpolation scheme.
+
+            Parameters
+            ----------
+            interpolation_order : :obj:`int`
+                0 refers to linear interpolation, 1 to quadratic interpolation.
```
Comment (fweik) [inline src/python/espressomd/lb.pyx]: Why not directly use strings for the interpolation order?

File: src/core/grid_based_algorithms/lbgpu_cuda.cu [hunk 8]
```diff
@@ -1740,87 +1747,19 @@ __device__ void calc_viscous_force(LB_nodes_gpu n_a, float *delta,
...
-      (delta[7] * delta_j[0]));
-  atomicAdd(
-      &(node_f.force_density[(1) * para->number_of_nodes + node_index[7]]),
-      (delta[7] * delta_j[1]));
-  atomicAdd(
-      &(node_f.force_density[(2) * para->number_of_nodes + node_index[7]]),
-      (delta[7] * delta_j[2]));
+                                LB_node_force_density_gpu node_f,
+                                bool three_point_coupling) {
+  int max_node = 8;
```
Comment (fweik) [inline src/core/grid_based_algorithms/lbgpu_cuda.cu]: This information should be encoded into the type of `node_index` and `delta`, this is very brittle...

File: src/core/grid_based_algorithms/lbgpu_cuda.cu [hunk 9]
```diff
@@ -2307,12 +2246,13 @@ __global__ void
 calc_fluid_particle_ia(LB_nodes_gpu n_a, CUDA_particle_data *particle_data,
                        float *particle_force, LB_node_force_density_gpu node_f,
                        LB_rho_v_gpu *d_v, bool couple_virtual,
-                       uint64_t philox_counter, float friction) {
+                       uint64_t philox_counter, float friction,
+                       float *lb_boundary_velocity, bool three_point_coupling) {
```
Comment (fweik) [inline src/core/grid_based_algorithms/lbgpu_cuda.cu]: Since there are only two coupling schemes, and this code is performance relevant, I think the coupling scheme should be selected statically and code for both schemes without the branches should be generated. E.g. make the coupling scheme a template parameter and instantiate both versions of this kernel.

**Review by fweik — CHANGES_REQUESTED** [review]

File: src/core/grid_based_algorithms/lb_interpolation.cpp (hunk 1 above)
Comment (KaiSzuttor) [reply src/core/grid_based_algorithms/lb_interpolation.cpp]: this is c++17

Comment (fweik) [reply src/core/grid_based_algorithms/lb_interpolation.cpp]: Ah yeah sorry, you have to do `static_cast<InterpolationOrder>(order)`.

Comment (KaiSzuttor) [reply src/core/grid_based_algorithms/lb_interpolation.cpp]: what about ```interpolation_order = static_cast<InterpolationOrder>(order);```?

Comment (KaiSzuttor) [reply src/core/grid_based_algorithms/lb_interpolation.cpp]: this is probably not such a good idea:
https://gcc.godbolt.org/z/Re_etN

Comment (fweik) [reply src/core/grid_based_algorithms/lb_interpolation.cpp]: That is fine here because the value is generated from an enum.

Comment (fweik) [reply src/core/grid_based_algorithms/lb_interpolation.cpp]: If you don't want that you can send the enum value via mpi, they can be serialized...

**Comment by KaiSzuttor** [comment]
@fweik

File: src/core/grid_based_algorithms/lb_interpolation.cpp [hunk 10]
```diff
@@ -1,17 +1,39 @@
...
+  boost::mpi::broadcast(comm_cart, interpolation_order, 0);
+}
+
 #if defined(LB) || defined(LB_GPU)
 
-namespace {
+void lb_lbinterpolation_set_interpolation_order(
+    InterpolationOrder const &order) {
+  interpolation_order = order;
+  boost::mpi::broadcast(comm_cart, interpolation_order, 0);
```
Comment (fweik) [inline src/core/grid_based_algorithms/lb_interpolation.cpp]: The mpi calls need to be the other way around, this is a deadlock.

**Review by fweik — CHANGES_REQUESTED** [review]

File: src/core/grid_based_algorithms/lb_interpolation.cpp (hunk 10 above)
Comment (KaiSzuttor) [reply src/core/grid_based_algorithms/lb_interpolation.cpp]: Could you please explain?

Comment (fweik) [reply src/core/grid_based_algorithms/lb_interpolation.cpp]: You are blocking on ` boost::mpi::broadcast` before the callback is invoked.

**Review by fweik — APPROVED** [review]

**Comment by RudolfWeeber** [comment]
I think, this pr was merged prematurely, I'm afraid.

This PR decreased the performance of the 2pt coupling by a factor of 3, 
I now have a time step of 1.2 sec instead of 0.4 sec for 500k particles.

If the reason for the drag cannot be removed, the changes to the 2pt coupling need to be reverted.
