### PR TITLE
CMake: Default with_scafacos = off, since it requries ELECTROSTATICS

### LINKED ISSUE #2414: Build fails when Scafacos is found
with
```
/home/espresso/build/src/core/config-features.cpp:128:2: error: #error Feature SCAFACOS requires ELECTROSTATICS
 #error Feature SCAFACOS requires ELECTROSTATICS
```

### PR DESCRIPTION
**Pull request by RudolfWeeber**
Fixes #2414.
@fweik

### CODE REVIEW

**Review by fweik — APPROVED** [review]

File: maintainer/CI/build_cmake.sh [hunk 1]
```diff
@@ -84,7 +84,7 @@ if [[ ! -z ${with_coverage+x} ]]; then
   bash <(curl -s https://codecov.io/env) &> /dev/null;
 fi
 
-cmake_params="-DCMAKE_BUILD_TYPE=$build_type -DPYTHON_EXECUTABLE=$(which python$python_version) -DWARNINGS_ARE_ERRORS=ON -DTEST_NP:INT=$check_procs $cmake_params"
+cmake_params="-DCMAKE_BUILD_TYPE=$build_type -DPYTHON_EXECUTABLE=$(which python$python_version) -DWARNINGS_ARE_ERRORS=ON -DTEST_NP:INT=$check_procs $cmake_params -DWITH_SCAFACOS=ON"
```
Comment (fweik) [inline maintainer/CI/build_cmake.sh:87]: I don't think you can do `-DWITH_SCAFACOS=ON` in the build script for all builds as there are containers where there is now scafacos; on these the build should fail now.

**Review by fweik — CHANGES_REQUESTED** [review]

**Comment by RudolfWeeber** [comment]
On Sun, Jan 06, 2019 at 11:51:26PM -0800, Florian Weik wrote:
> fweik requested changes on this pull request.
> 
> 
> 
> > @@ -84,7 +84,7 @@ if [[ ! -z ${with_coverage+x} ]]; then
>    bash <(curl -s https://codecov.io/env) &> /dev/null;
>  fi
>  
> -cmake_params="-DCMAKE_BUILD_TYPE=$build_type -DPYTHON_EXECUTABLE=$(which python$python_version) -DWARNINGS_ARE_ERRORS=ON -DTEST_NP:INT=$check_procs $cmake_params"
> +cmake_params="-DCMAKE_BUILD_TYPE=$build_type -DPYTHON_EXECUTABLE=$(which python$python_version) -DWARNINGS_ARE_ERRORS=ON -DTEST_NP:INT=$check_procs $cmake_params -DWITH_SCAFACOS=ON"
> 
> I don't think you can do `-DWITH_SCAFACOS=ON` in the build script for all builds as there are containers where there is now scafacos; on these the build should fail now.
Just like WITH_CUDA, the switch enables the detection, not the
actual use.

**Review by fweik — APPROVED** [review]

**Comment by fweik** [comment]
Fine with me, the main point was to avoid the build failures.
