### PR TITLE
Fix polymer generation

### LINKED ISSUE #3483: Polymer generation does not obey minimum image convention

### PR DESCRIPTION
**Pull request by fweik**
Fixes #3483.

Description of changes:
 - Obey minimum image convention
 - To not falsely pre-populate all positions with the zero vector
 - Refactored generation loop to make it more redable
 - Check for constraint violations between starting positions

### CODE REVIEW

File: src/core/polymer.cpp [hunk 1]
```diff
@@ -123,91 +119,90 @@ draw_polymer_positions(PartCfg &partCfg, int const n_polymers,
...
+    if (is_valid_pos(start_positions[p])) {
+      positions[p].push_back(start_positions[p]);
     } else {
-      positions[p][0] = start_positions[p];
+      throw std::runtime_error("Invalid start positions.");
     }
   }
 
-  // create remaining monomers' positions
+  /* Draw a monomer position, obeying angel and starting position
```
Comment (jngrad) [inline src/core/polymer.cpp]:
```suggestion
  /* Draw a monomer position, obeying angle and starting position
```

File: src/core/polymer.cpp [hunk 2]
```diff
@@ -123,91 +119,90 @@ draw_polymer_positions(PartCfg &partCfg, int const n_polymers,
...
+   * constraints where apropriate. */
```
Comment (jngrad) [inline src/core/polymer.cpp]:
```suggestion
   * constraints where appropriate. */
```

**Review by jngrad — CHANGES_REQUESTED** [review]

**Comment by jngrad** [comment]
This is a lot better! The `polymer_linear.py` test doesn't fail anymore, even with a different seed at each execution. This isn't the first time that a bug is ignored by setting a magic seed in the test script...

**Review by jngrad — APPROVED** [review]
