### PR TITLE
Linked cell list loop for steepest descent with shared memory parallelisation

### LINKED ISSUE #5141: steepest descent broken with shared memory paralelllism
the steepest descent in below code converges fine when building Espresso without shared memory parallelism.

With shard memory parallelism enabled, the loop never terminates:
the median force decays as expected, but the maximum force does not. 
I.e., most likely, with shared mem parallelizm enabled, either a few particles are missed by the steepest descent, or a Cartesian coordinate is missed.

Here's the code (in the end, particles interacting by an attracive Lj interaciton):

```python
import espressomd
import espressomd.observables
from pint import UnitRegistry
import numpy as np
from tqdm import tqdm
u = UnitRegistry()

Q_ = u.Quantity

# --- Fundamental constants (CODATA exact where defined) ---
kB = Q_(1.380649e-23, "joule/kelvin")         # Boltzmann constant
T = Q_(298.15, "kelvin")                      # temperature
u.define(f"kT = {(kB*T).to('joule')}") 
u.define("e = 1.602176634e-19 coulomb")           # elementary charge

# --- TIP4P/2005 Lennard-Jones (oxygen site) ---
sigma = Q_(3.1589, "angstrom")
eps_over_kB = Q_(93.2, "kelvin")              # ε/kB = 93.2 K
eps_LJ = eps_over_kB * kB                     # ε in joules

# Simulation units: 
# * energy: kT
# * mass: atomic mass unit
# * length: nm
# * charge: unit chage





L =2.5 #nm

# number density of water molecules
WATER_DENSITY = Q_(0.96, "g/cm^3")
O_MASS = 15.9994 # amu
H_MASS = 1.008 # amu
NA = Q_(6.02214076e23, "1 / mole")            # Avogadro constant
TIP4P_MASS=Q_(O_MASS+2*H_MASS,"g/mole")
RHO_N = (WATER_DENSITY/TIP4P_MASS*NA).to("1/nm^3").magnitude

OO_EPSILON = (eps_LJ /(kB*T)).to("dimensionless").magnitude
OO_SIGMA = 0.31589   # nm



system = espressomd.System(box_l=[L,L,L])

n_waters = int(RHO_N*system.volume())
system.part.add(pos=np.random.random((n_waters,3))*system.box_l)

system.non_bonded_inter[0,0].lennard_jones.set_params(epsilon=OO_EPSILON,sigma=OO_SIGMA,cutoff=2.5*OO_SIGMA,shift="auto")
system.time_step = 0.01
system.cell_system.skin=0.1

system.integrator.set_steepest_descent(f_max=1,max_displacement=0.01,gamma=1E-10)
system.integrator.run(200)

while np.amax(np.abs(system.part.all().f))>10:
    med_force = np.median(np.abs(system.part.all().f))
    print(med_force,np.amax(np.abs(system.part.all().f)))
    max_disp=0.0005
    system.integrator.set_steepest_descent(f_max=0,max_displacement=max_disp,gamma=max_disp/med_force)
    system.integrator.run(100)
system.integrator.set_vv()
print("Done")
```

### PR DESCRIPTION
**Pull request by hidekb**
Fixes #5141

To solve #5141, we implemented a link cell loop for steepest descent with sheared memory parallelisation because the 2D array Verlet list causes this issue.

Description of changes:
- `id_to_index` changed to a member variable of CellStructure
- To recognise weather steepest_descent is running, we added integ_switch as an argument to `cabana_short_range()`
- To impmenet link cell loop using Kokkos::parallel_for, we added the function `link_cell_kokkos()` in short_range_cabana.hpp and `link_cell_loop()` in CellStructure.hpp

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
Having `in_steepest_descent` as state of the CellStructure might be a bit error-prone in the future.
Please check whether this cannot be determined from the integ_switch or propagation as in integrate.cpp.


Also, the RegularDecomposition hase a use_verlet_lists attribute. This should also be taken into account:

so: if (integration swtich == steepest descent) or (not cell structure use verlet lists) {
  linked cell loop
} else {
  verlet lsit loop
}

**Comment by hidekb** [comment]
I add `integration_switch` as an argument to `cabana_short_range()`, where it controls whether the linked cell loop is used.

File: src/core/forces_cabana.hpp [hunk 1]
```diff
@@ -114,7 +114,7 @@ struct ForcesKernel {
     auto const dist = d.norm();
 
 #if defined(ESPRESSO_EXCLUSIONS) or defined(ESPRESSO_DPD) or                   \
-    defined(ESPRESSO_DIPOLES)
+    defined(ESPRESSO_THOLE) or defined(GAY_BERNE) or defined(ESPRESSO_DIPOLES)
```
Comment (jngrad) [inline src/core/forces_cabana.hpp]: here and elsewhere, don't forget to add the `ESPRESSO_` prefix to all ESPResSo features :-)

Comment (hidekb) [reply src/core/forces_cabana.hpp]: I added `ESPRESSO_` prefix.

Comment (jngrad) [reply src/core/forces_cabana.hpp]: it's still missing from `SHARED_MEMORY_PARALLELISM`

Comment (hidekb) [reply src/core/forces_cabana.hpp]: Good catch! Sorry about that. I have fixed it.

**Review by jngrad — DISMISSED** [review]
Scenario 1 in #5144 is now also fixed.

**Review by jngrad — APPROVED** [review]
