### PR TITLE
Lattice

### LINKED ISSUE #2556: LB: lattice_switch is ambiguous
The global variable `lattice_switch` is currently defined as:
https://github.com/espressomd/espresso/blob/0682e84736bd6d8b0131078a0551d35dd1a920c6/src/core/grid_based_algorithms/lattice.hpp#L34-L43

And it is used like this:
https://github.com/espressomd/espresso/blob/0682e84736bd6d8b0131078a0551d35dd1a920c6/src/core/grid_based_algorithms/lb_particle_coupling.cpp#L48-L59

A few issues here:
* the numerical values are not connected to the variable, causing documentation decay (the Doxygen blocks are already outdated)
* the `#ifdef` statements seem redundant with the global variable; shouldn't writing `lattice_switch = LATTICE_LB_GPU` when LB_GPU isn't compiled in raise an exception?
* is the statement `lattice_switch = LATTICE_LB & LATTICE_LB_GPU` legal (documentation says yes) and if so, in a switch, when should LB CPU evaluation happen before LB GPU evaluation?

### PR DESCRIPTION
**Pull request by KaiSzuttor**
edit: fixes #2556

### CODE REVIEW

File: src/core/communication.cpp [hunk 1]
```diff
@@ -866,17 +866,17 @@ void mpi_sync_topo_part_info_slave(int, int) {
 
 /******************* REQ_BCAST_LBPAR ********************/
 
-void mpi_bcast_lb_params(int field, int value) {
+void mpi_bcast_lb_params(LBParam field, int value) {
 #ifdef LB
-  mpi_call(mpi_bcast_lb_params_slave, field, value);
-  mpi_bcast_lb_params_slave(field, value);
+  mpi_call(mpi_bcast_lb_params_slave, static_cast<int>(field), value);
```
Comment (KaiSzuttor) [inline src/core/communication.cpp:871]: why do you cast? you can directly broadcast the enum class

Comment (jngrad) [reply src/core/communication.cpp:871]: an enum class doesn't implicitly cast to an int, therefore we get `cannot convert ‘LBParam’ to ‘int’ for argument ‘2’ to ‘void mpi_call(void (*)(int, int), int, int)’`

**Comment by fweik** [comment]
@jngrad please resolve the merge conflict.

**Comment by jngrad** [comment]
I had the same issue when merging into fweik's branch. Not sure why git is making things so difficult.

File: src/core/grid_based_algorithms/lb_interface.hpp [hunk 2]
```diff
@@ -58,14 +54,19 @@ void lb_lbfluid_set_rng_state(uint64_t counter);
 const Lattice &lb_lbfluid_get_lattice();
 
 /**
- * @brief Get the global variable lattice_switch which defines wether NONE, CPU
- * or GPU LB is active.
+ * @brief Get the global variable @ref lattice_switch.
+ *
+ * Function to be called from Cython.
+ */
+int lb_lbfluid_get_lattice_switch_cython();
```
Comment (fweik) [inline src/core/grid_based_algorithms/lb_interface.hpp]: Why is this function needed? scoped enums can be used in cython, please deal with cython stuff in the cython code.

File: src/core/grid_based_algorithms/lb_interface.cpp [hunk 3]
```diff
@@ -1274,35 +1261,39 @@ void lb_lbnode_set_pop(const Vector3i &ind, const Vector19d &p_pop) {
...
+ActiveLB lb_lbfluid_get_lattice_switch() { return lattice_switch; }
+
+int lb_lbfluid_get_lattice_switch_cython() {
+  return static_cast<int>(lattice_switch);
+}
 
-void lb_lbfluid_on_lb_params_change(int field) {
-  if (field == LBPAR_AGRID) {
+void lb_lbfluid_on_lb_params_change(LBParam field) {
+  if (field == LBParam::AGRID) {
```
Comment (fweik) [inline src/core/grid_based_algorithms/lb_interface.cpp]: `switch(field)` ...

**Review by fweik — CHANGES_REQUESTED** [review]

File: src/core/grid_based_algorithms/lb_interface.cpp (hunk 3 above)
Comment (jngrad) [reply src/core/grid_based_algorithms/lb_interface.cpp]: done

File: src/core/grid_based_algorithms/lb_interface.hpp (hunk 2 above)
Comment (jngrad) [reply src/core/grid_based_algorithms/lb_interface.hpp]: I already looked for a better alternative last week, but Cython support for exported C enums is limited:
* `cdef enum ActiveLB: NONE = 0, CPU, GPU` in .pxd, then in .pyx:
   * `fun(ActiveLB.CPU)` -> `error: ‘CPU’ was not declared in this scope: fun(CPU)`
   * `fun(<ActiveLB> ActiveLB.CPU)` -> `error: ‘CPU’ was not declared in this scope: fun((enum ActiveLB)CPU)`
* `cdef enum enum_ActiveLB "ActiveLB": NONE = 0, CPU, GPU` in .pxd, then in .pyx:
   * `fun(enum_ActiveLB.CPU)` -> `error: ‘CPU’ was not declared in this scope: fun(CPU)`
* same observations with `ctypedef` instead of `cdef`
* there is a namespace for pure Python enums, though

Is the new solution with two enums (f009b72) satisfactory?

Comment (fweik) [reply src/core/grid_based_algorithms/lb_interface.hpp]: You can use them like this (example from the LB interface):

```cython
      cdef cppclass InterpolationOrder:
            pass

    cdef extern from "grid_based_algorithms/lb_interpolation.hpp" namespace "InterpolationOrder":
        cdef InterpolationOrder linear
        cdef InterpolationOrder quadratic
```

I think this should also work for return values.

Comment (jngrad) [reply src/core/grid_based_algorithms/lb_interface.hpp]: Ok, it should work now. It's kind of annoying the exported enum values cannot be grouped in a Python namespace (`cdef ActiveLB ActiveLB_CPU "CPU"` didn't work).

Comment (fweik) [reply src/core/grid_based_algorithms/lb_interface.hpp]: Yes, it's not nice. Did you see https://github.com/cython/cython/issues/1603#issuecomment-324602083 ?

Comment (jngrad) [reply src/core/grid_based_algorithms/lb_interface.hpp]: Saw it last week, but forgot to try it... Let's see if all compilers accept it.

Comment (jngrad) [reply src/core/grid_based_algorithms/lb_interface.hpp]: Looks like a no on Cython 0.23.4 (excepted container `empty`), but a yes on 0.25.2 and above. Should I just revert the last commit?

Comment (fweik) [reply src/core/grid_based_algorithms/lb_interface.hpp]: Yes, just revert to the solution without the namespace.

**Review by fweik — APPROVED** [review]
