### PR TITLE
Fix Scafacos code

### LINKED ISSUE #2833: SCAFACOS_DIPOLES broken
`SCAFACOS_DIPOLES` isn't tested anymore (it was in 4.0.2 according to [codecov](https://codecov.io/gh/espressomd/espresso/src/release-4.0.2/src/core/scafacos/Scafacos.cpp)) and doesn't compile:
```
/local/es/src/core/electrostatics_magnetostatics/scafacos.cpp:96:13: error: 'Vector3d' does not name a type
       const Vector3d dip = p.calc_dip();
             ^~~~~~~~
/local/es/src/core/electrostatics_magnetostatics/scafacos.cpp:97:25: error: 'dip' was not declared in this scope
       dipoles.push_back(dip[0]);
                         ^~~
```

### PR DESCRIPTION
**Pull request by jngrad**
Fixes #2833

Description of changes:
- fix namespace issue
- put  `SCAFACOS_DIPOLES` back into CI

### CODE REVIEW

File: src/core/electrostatics_magnetostatics/scafacos.cpp [hunk 1]
```diff
@@ -113,43 +113,44 @@ void ScafacosData::update_particle_forces() const {
...
-      // scafacos
-      double f[3];
-      f[0] = fields[it_f + 0] * dip[0] + fields[it_f + 1] * dip[1] +
-             fields[it_f + 2] * dip[2];
-      f[1] = fields[it_f + 1] * dip[0] + fields[it_f + 3] * dip[1] +
-             fields[it_f + 4] * dip[2];
-      f[2] = fields[it_f + 2] * dip[0] + fields[it_f + 4] * dip[1] +
-             fields[it_f + 5] * dip[2];
+      // where the numbers refer to indices in the "field" output from scafacos
+      Utils::Vector3d const f = {
```
Comment (fweik) [inline src/core/electrostatics_magnetostatics/scafacos.cpp]: Wouldn't it be clearer to just construct the matrix and then do a product? like
```
auto const G = Vector<Vector3d, 3>>{{fields[it_f + 0], ...}, ...};
auto const f = G * dip;
```
?

Comment (jngrad) [reply src/core/electrostatics_magnetostatics/scafacos.cpp]: Thanks! This is a lot better.

**Review by fweik — APPROVED** [review]
