### PR TITLE
Fix tabulated bond memory leaks

### LINKED ISSUE #3906: Memory leaks in tabulated bonds
The head node callback `mpi_bcast_ia_params()`and its worker node callback `mpi_bcast_ia_params_slave()` are mostly identical and could be merged into a single callback, with a conditional on the MPI rank to manage manual memory allocation on worker nodes. This callback could then be moved from `communication.cpp` to e.g. `src/core/bonded_interactions/bonded_interaction_data.cpp`.

Right now the worker implementation allocates a pointer with `new` and overwrites the old pointer without a proper `delete`, leading to a memory leak every time a tabulated bond is updated, when running with 2 MPI ranks or more. Here is the relevant code:

https://github.com/espressomd/espresso/blob/f760050199b94226b9127b309bfa7db569507605/src/core/communication.cpp#L336-L345

Adding `delete` at L344 before changing the pointer doesn't solve the issue, because the MPI communication at L336 already overwrote the address of the allocated memory on the worker node with the address to the allocated memory on the head node.

Solving this requires adding a `delete` before the communication at L336, although it would be better to write a proper serialization method with `boost::serialization` to avoid communicating pointer members. The serialization can also take care of packing the vectors. In fact, there is already a `TabulatedPotential::serialization()` method, so it's just a matter of calling it from the bonded interactions code.

Here is a MWE to trigger the memory leak:
```python
import numpy as np
import espressomd
from espressomd.interactions import TabulatedDistance
import time

system = espressomd.System(box_l=[10] * 3)
system.time_step = 0.01
system.cell_system.skin = 0.4

a = np.arange(4000000)
print('array size: {:.0f} MB'.format(a.size * a.itemsize / 1024**2))

print('start allocation')
system.bonded_inter.add(TabulatedDistance(min=0.1, max=2, energy=a, force=a))
for i in range(10):
    system.bonded_inter[0] = TabulatedDistance(min=0.1, max=2, energy=a, force=a)
    time.sleep(0.1)

print('stop allocation')
time.sleep(5)
```
```sh
mpiexec -n 2 ./pypresso mwe.py
```

Takes 1400 MB of RAM on 2fbea6e967. After adding a `delete`, takes "only" 900 MB of RAM, which is still larger than the expected 200 MB, so there might be another memory leak... possibly somewhere around the `TabulatedPotential` code, because the non-bonded tabulated interaction also consumes a lot of RAM when its parameters are updated in a loop. This second memory leak also has a surprising garbage collection behavior: memory seems to be allocated for a new container before the previous container was deallocated, which shows up in `htop` as RAM bouncing back and forth between two values after each loop iteration. That's why there is this `sleep(5)` statement at the end of the MWE, to get the final 900 MB of RAM consumption (peak RAM consumption is 1050 MB).

### PR DESCRIPTION
**Pull request by jngrad**
Fixes #3906

Description of changes:
- fix dangling pointers in tabulated bonds
- reduce code duplication in callbacks

### CODE REVIEW

File: src/core/communication.cpp [hunk 1]
```diff
@@ -335,14 +335,15 @@ void mpi_bcast_ia_params_slave(int i, int j) {
...
+    }
     MPI_Bcast(&(bonded_ia_params[i]), sizeof(Bonded_ia_parameters), MPI_BYTE, 0,
               comm_cart);
     /* For tabulated potentials we have to send the tables extra */
     if (is_tabulated_bond(bonded_ia_params[i].type)) {
-      auto *tab_pot = new TabulatedPotential();
-      boost::mpi::broadcast(comm_cart, *tab_pot, 0);
-
-      bonded_ia_params[i].p.tab.pot = tab_pot;
+      bonded_ia_params[i].p.tab.pot = new TabulatedPotential();
```
Comment (KaiSzuttor) [inline src/core/communication.cpp]: haven't looked into the code, but can't we use smart pointers?

Comment (jngrad) [reply src/core/communication.cpp]: I don't think so: we overwrite the memory block of the bond object on worker nodes with a bytestring of the same object from the head node, so the counter from a `shared_ptr` would be overwritten. As for `unique_ptr`, in the line you highlighted, we do an assignment, so the smart pointer goes out of scope and gets garbage-collected... but it contains a random memory address (because of the bytestring deserialization a few lines above), which is a recipe for segmentation faults.

Comment (KaiSzuttor) [reply src/core/communication.cpp]: i'm not sure i'm following... but it sounds like this is a place for larger scale refactoring which is out of scope of this pull request?

Comment (jngrad) [reply src/core/communication.cpp]: the correct way would be to write boost serialization methods, which can handle pointer members out of the box, e.g.
```c++
struct Tabulated_bond_parameters {
  int type;
  TabulatedPotential *pot;

private:
  friend boost::serialization::access;
  template <typename Archive>
  void serialize(Archive &ar, long int /* version */) {
    ar &type;
    ar &pot;
  }
};
```
but there is no guarantee that we are overwriting a bond type with the same bond type, so we would have to add destructors too... Not sure if this is worth the effort, if our long-term goal is to replace this interaction communication infrastructure with a python setter.

Comment (jngrad) [reply src/core/communication.cpp]: Also, a much more promising refactoring goal is breaking the dependency on `MpiCallbacks.hpp` from consumers of MPI callbacks ([fix-3906...fix-3907-p1](https://github.com/jngrad/espresso/compare/fix-3906...fix-3907-p1)), which as a side effect is removing global variables and removing prototypes of MPI worker functions from header files.

Comment (KaiSzuttor) [reply src/core/communication.cpp]: > Also, a much more promising refactoring goal is breaking the dependency on `MpiCallbacks.hpp` from consumers of MPI callbacks ([fix-3906...fix-3907-p1](https://github.com/jngrad/espresso/compare/fix-3906...fix-3907-p1)), which as a side effect is removing global variables and removing prototypes of MPI worker functions from header files.

Isn't that totally orthogonal to the memory leak issue?

Comment (KaiSzuttor) [reply src/core/communication.cpp]: > the correct way would be to write boost serialization methods, which can handle pointer members out of the box, e.g.
> 
> ```c++
> struct Tabulated_bond_parameters {
>   int type;
>   TabulatedPotential *pot;
> 
> private:
>   friend boost::serialization::access;
>   template <typename Archive>
>   void serialize(Archive &ar, long int /* version */) {
>     ar &type;
>     ar &pot;
>   }
> };
> ```
> 
> but there is no guarantee that we are overwriting a bond type with the same bond type, so we would have to add destructors too... Not sure if this is worth the effort, if our long-term goal is to replace this interaction communication infrastructure with a python setter.

sorry, if that has been discussed and i don't remember it anymore... Do we have some design plans for the interaction stuff already?

**Comment by RudolfWeeber** [comment]
>sorry, if that has been discussed and i don't remember it anymore... Do we have some design plans for the interaction stuff already?

My understanding is that

*	Actors, bonded and non-bonded interactions should be used via the script-interface, which handles the broadcasting of parameters, so the comm infrastructure for it in the core goes away
*	The BondedInteractionParams type should be a variant rather than a union
*	Since the communication is handled by the script interface, bonds are set in the core on the node level by assignment. As long as the strucs holding the parameters for the individual bodns either don’t contain manual memory management or provide a destructor, it should not be possible to loose memory anymore.

**Comment by KaiSzuttor** [comment]
so think we should now merge this but also stop refactoring the existing infrastructure if the plan is to move most of the parts to the sciptinterface.

File: src/core/bonded_interactions/bonded_tab.cpp [hunk 2]
```diff
@@ -37,6 +37,11 @@ int tabulated_bonded_set_params(int bond_type,
   make_bond_type_exist(bond_type);
 
   /* set types */
+  if (bonded_ia_params[bond_type].type == BONDED_IA_TABULATED_DISTANCE or
+      bonded_ia_params[bond_type].type == BONDED_IA_TABULATED_ANGLE or
+      bonded_ia_params[bond_type].type == BONDED_IA_TABULATED_DIHEDRAL) {
+    delete bonded_ia_params[bond_type].p.tab.pot;
```
Comment (KaiSzuttor) [inline src/core/bonded_interactions/bonded_tab.cpp:43]: cant't you just check for ```nullptr```?

Comment (KaiSzuttor) [reply src/core/bonded_interactions/bonded_tab.cpp:43]:
``` c++
if (bonded_ia_params[bond_type].p.tab.pot) delete bonded_ia_params[bond_type].p.tab.pot;
```

**Comment by fweik** [comment]
IMHO, #3019 should be fixed before this. This correct way to solve this is to have the tabulated bond manage it's own memory (via unique ptr or similar), but this is not possible as long as the bond parameters is a `union`, because you can only have trivial types in a union. This is why I opened 3019 in the first place. There is no way to fix the memory leak which is not a hack in the sense that it mixes unrelated concerns.

File: src/core/bonded_interactions/bonded_tab.cpp (hunk 2 above)
Comment (jngrad) [reply src/core/bonded_interactions/bonded_tab.cpp:43]: Actually this would raise a Clang-Tidy warning because you can simplify it to
```c++
delete bonded_ia_params[bond_type].p.tab.pot;
```
which is safe on a `nullptr`.
However, this would also trigger a segfault, because you can create a tabulated bond on top of an existing FENE bond, in which case `.p.tab.pot` contains a random address. You can overwrite an bond existing bond in ESPResSo, this is used for example in `testsuite/python/interactions_bonded_interface.py`.

**Review by RudolfWeeber — APPROVED** [review]

**Comment by RudolfWeeber** [comment]
Let's merge this, also due to the comment fixes contained in the PR.
The "fix" for the mem leak is, of course, a hack.
It will go away, once we convert the bond parameters to a Variant and let the script interface do the parameter broadcasting.
